# Generated by Django 2.1.4 on 2018-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluApp', '0003_produtosservicos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutosServicos',
        ),
        migrations.AlterField(
            model_name='credito',
            name='data_proposta',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
