# Generated by Django 2.1.4 on 2018-12-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluApp', '0004_auto_20181215_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do cliente'),
        ),
    ]
