# Generated by Django 2.1.4 on 2018-12-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluApp', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='categoria',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
    ]
