# Generated by Django 2.1.4 on 2018-12-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluApp', '0007_message_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='categoria',
            field=models.CharField(choices=[('SALDO', 'Pedir saldo'), ('EXTRATO', 'Pedir extrato'), ('ABERTURA_CONTA', 'Abertura de conta'), ('OUTRI', 'Outro')], default='SALDO', max_length=2),
        ),
    ]
