# Generated by Django 2.1.4 on 2018-12-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluApp', '0008_auto_20181217_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
