# Generated by Django 2.1.4 on 2020-01-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluApp', '0009_auto_20181217_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='categoria',
            field=models.CharField(choices=[('SALDO', 'Pedir saldo'), ('EXTRATO', 'Pedir extrato'), ('ABERTURA_CONTA', 'Abertura de conta'), ('CONFIRMACAO DE PAGAMENTO', 'Confirmacao de pagamento'), ('PEDIDO DE FX', 'Pedido de FX'), ('OUTRO', 'Outro')], default='SALDO', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='message',
            name='nome',
            field=models.CharField(max_length=5),
        ),
    ]
