# Generated by Django 2.1.4 on 2018-12-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181217_0959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
